# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_model.Model')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description_en', models.TextField(null=True)),
                ('in_navigation_bar', models.BooleanField(default=False, verbose_name='appears in main menu')),
                ('position_in_nav_bar', models.IntegerField()),
                ('_slug', models.SlugField(max_length=100)),
            ],
            bases=('core_model.model',),
        ),
    ]
