# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_model.Model')),
            ],
            bases=('core_model.model',),
        ),
        migrations.CreateModel(
            name='Behaviour',
            fields=[
                ('model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_model.Model')),
            ],
            bases=('core_model.model',),
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('behaviour_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_model.Behaviour')),
                ('label_en', models.CharField(max_length=255)),
            ],
            bases=('core_model.behaviour',),
        ),
        migrations.CreateModel(
            name='UseACategoryOfEntity',
            fields=[
                ('behaviour_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_model.Behaviour')),
                ('use_or_dontuse', models.BooleanField()),
            ],
            bases=('core_model.behaviour',),
        ),
        migrations.AddField(
            model_name='alternative',
            name='from_behaviour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='core_model.Behaviour'),
        ),
        migrations.AddField(
            model_name='alternative',
            name='to_behaviour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_alternative_to', to='core_model.Behaviour'),
        ),
        migrations.AddField(
            model_name='alternative',
            name='topicm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_model.Topic'),
        ),
    ]
