# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-02 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_model', '0004_otherbehaviour_description_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherbehaviour',
            old_name='label_en',
            new_name='title_en',
        ),
    ]
