# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-13 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_model', '0005_auto_20160802_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAlternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestBehaviour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leaf', models.BooleanField()),
                ('name', models.CharField(max_length=500)),
                ('parents', models.ManyToManyField(related_name='children', to='core_model.TestEntity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestEntityThatHaveProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_level', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_entity', models.ManyToManyField(related_name='to_relations', to='core_model.TestEntity')),
                ('to_entity', models.ManyToManyField(related_name='from_relations', to='core_model.TestEntity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description_en', models.TextField(null=True)),
                ('in_navigation_bar', models.BooleanField(default=False, verbose_name='appears in main menu')),
                ('position_in_nav_bar', models.IntegerField()),
                ('_slug', models.SlugField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestHabit',
            fields=[
                ('testbehaviour_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_model.TestBehaviour')),
                ('label_en', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('core_model.testbehaviour',),
        ),
        migrations.CreateModel(
            name='TestOtherBehaviour',
            fields=[
                ('testbehaviour_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_model.TestBehaviour')),
                ('title_en', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('core_model.testbehaviour',),
        ),
        migrations.CreateModel(
            name='TestUseAKindOfEntity',
            fields=[
                ('testbehaviour_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_model.TestBehaviour')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_model.testbehaviour',),
        ),
        migrations.AddField(
            model_name='testentitythathaveproperties',
            name='properties',
            field=models.ManyToManyField(to='core_model.TestRelation'),
        ),
        migrations.AddField(
            model_name='testentitythathaveproperties',
            name='target_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ethp', to='core_model.TestEntity'),
        ),
        migrations.AddField(
            model_name='testalternative',
            name='from_behaviours',
            field=models.ManyToManyField(related_name='alternatives', to='core_model.TestBehaviour'),
        ),
        migrations.AddField(
            model_name='testalternative',
            name='to_behaviour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_alternative_to', to='core_model.TestBehaviour'),
        ),
        migrations.AddField(
            model_name='testalternative',
            name='topics',
            field=models.ManyToManyField(to='core_model.TestTopic'),
        ),
        migrations.AddField(
            model_name='testuseakindofentity',
            name='entity_with_properties',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_model.TestEntityThatHaveProperties'),
        ),
    ]
