# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-13 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_model', '0006_auto_20160913_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAssociation',
            fields=[
                ('testentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_model.TestEntity')),
                ('description', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_model.testentity',),
        ),
        migrations.CreateModel(
            name='TestCompany',
            fields=[
                ('testentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_model.TestEntity')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_model.testentity',),
        ),
        migrations.CreateModel(
            name='TestCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_en', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_en', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestProduct',
            fields=[
                ('testentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_model.TestEntity')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_model.testentity',),
        ),
        migrations.AddField(
            model_name='testassociation',
            name='country',
            field=models.ManyToManyField(to='core_model.TestCountry'),
        ),
        migrations.AddField(
            model_name='testassociation',
            name='lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_model.TestLanguage'),
        ),
    ]
