# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-13 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_model', '0007_auto_20160913_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='testalternative',
            name='foo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
