# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0038_auto_20150925_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumeAtACompany',
            fields=[
                ('behaviour_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api2.Behaviour')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api2.Company', verbose_name='Consume at ...')),
            ],
            bases=('api2.behaviour',),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='from_rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='api2.HasImpactOn', verbose_name='This impact [ /rest/hasimpacton ]'),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='to_rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_alternative_of', to='api2.Behaviour', verbose_name='has this alternative [ /rest/habit OU /rest/consumeaproduct ]'),
        ),
        migrations.AlterField(
            model_name='alternativetomainimpact',
            name='from_rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='api2.MainImpact', verbose_name='This Main Impact [ /rest/mainimpact ]'),
        ),
        migrations.AlterField(
            model_name='alternativetomainimpact',
            name='to_rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_alternative_of_main_impact', to='api2.Behaviour', verbose_name='has this alternative [ /rest/habit OU /rest/behaviour ]'),
        ),
        migrations.AlterField(
            model_name='behaviour',
            name='topic',
            field=models.ManyToManyField(to='api2.Topic'),
        ),
        migrations.AlterField(
            model_name='hasimpacton',
            name='becauseOf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_impact_on', to='api2.Relation', verbose_name='because of [ /rest/relation ]'),
        ),
        migrations.AlterField(
            model_name='hasimpacton',
            name='behavior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_impact_on', to='api2.Behaviour', verbose_name='This behaviour [ /rest/consumeaproduct OU /rest/habit ]'),
        ),
        migrations.AlterField(
            model_name='mainimpact',
            name='impactCateg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api2.ImpactCateg', verbose_name='has an main impact on'),
        ),
        migrations.AlterField(
            model_name='mainimpact',
            name='topics',
            field=models.ManyToManyField(to='api2.Topic'),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='relation',
            name='from_rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='api2.Entity', verbose_name='This Object'),
        ),
        migrations.AlterField(
            model_name='source',
            name='topic',
            field=models.ManyToManyField(null=True, to='api2.Topic'),
        ),
    ]
