# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0041_auto_20160426_1806'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImpactLeve2',
            new_name='ImpactLevel2',
        ),
        migrations.AlterField(
            model_name='behaviour',
            name='topic',
            field=models.ManyToManyField(to='api2.Topic'),
        ),
        migrations.AlterField(
            model_name='mainimpact',
            name='topics',
            field=models.ManyToManyField(to='api2.Topic'),
        ),
        migrations.AlterField(
            model_name='source',
            name='topic',
            field=models.ManyToManyField(null=True, to='api2.Topic'),
        ),
    ]
