# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0042_auto_20160426_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactlevel2',
            name='parent',
            field=models.ManyToManyField(to='api2.ImpactLevel1'),
        ),
        migrations.AddField(
            model_name='impactlevel3',
            name='parent',
            field=models.ManyToManyField(to='api2.ImpactLevel2'),
        ),
        migrations.AlterField(
            model_name='behaviour',
            name='topic',
            field=models.ManyToManyField(to='api2.Topic'),
        ),
        migrations.AlterField(
            model_name='mainimpact',
            name='topics',
            field=models.ManyToManyField(to='api2.Topic'),
        ),
        migrations.AlterField(
            model_name='source',
            name='topic',
            field=models.ManyToManyField(to='api2.Topic'),
        ),
    ]
